version: '2'
services:
    haipin-app:
        image: haipin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://haipin-mysql:3306/haipin?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    haipin-mysql:
        extends:
            file: mysql.yml
            service: haipin-mysql
